# Generated by Django 5.0.3 on 2024-04-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='tasks',
            field=models.ManyToManyField(related_name='variants', to='tasks.task'),
        ),
    ]
