# Generated by Django 5.0.3 on 2024-04-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_usertask_uservariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sort_index',
            field=models.IntegerField(default=0),
        ),
    ]
