# Generated by Django 5.0.3 on 2024-04-22 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_usertask_pricer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['sort_index']},
        ),
        migrations.DeleteModel(
            name='UserVariant',
        ),
    ]
