# Generated by Django 5.0.3 on 2024-05-10 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_options_delete_uservariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typetask',
            name='type_group',
        ),
        migrations.RemoveField(
            model_name='task',
            name='type_task',
        ),
        migrations.DeleteModel(
            name='TypeGroup',
        ),
        migrations.DeleteModel(
            name='TypeTask',
        ),
    ]
