# Generated by Django 5.0.3 on 2024-05-10 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_task_task_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='text_solution',
        ),
    ]
