# Generated by Django 5.0.3 on 2024-05-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_remove_task_text_solution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['sort_index'], 'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AlterModelOptions(
            name='usertask',
            options={'verbose_name': 'Решенное задание', 'verbose_name_plural': 'Решенные задания'},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'verbose_name': 'Вариант', 'verbose_name_plural': 'Варианты'},
        ),
        migrations.AlterField(
            model_name='variant',
            name='tasks',
            field=models.ManyToManyField(related_name='tasks', to='tasks.task'),
        ),
    ]
